[package]
name = "intro_to_rust"
version = "0.1.0"
authors = ["Anthony Loughlin <Anthony_Loughlin@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
fstrings = "0.2.2"
ferris-says = "0.1"